schema = "npa.package.v0.1"
package = "npa-std"
version = "0.1.0"
license = "MIT"
description = "Legacy compatibility npa standard-library fixture for SRA-02."

core_spec = "npa.core.v0.1"
kernel_profile = "npa.kernel.v0.1"
certificate_format = "npa.certificate.canonical.v0.1"
checker_profile = "npa.checker.reference.v0.1"

[policy]
allow_custom_axioms = false
allowed_axioms = []

[[modules]]
module = "Std.Logic.Eq"
source = "Std/Logic/Eq/source.npa"
certificate = "Std/Logic/Eq/certificate.npcert"
producer_profile = "std-library-legacy-core-builder"
expected_source_hash = "sha256:347698ca0bc89aca3e76390d960bec805853015352dc93386fbbf7b4d710ea55"
expected_certificate_file_hash = "sha256:7aa25a1adf44de35cdaaa514484c1220fec0e543d3f65803805b5e6efc5b36a1"
expected_export_hash = "sha256:b78b442d5f593458cc12f079b59e3c70259c0bec4967511e1a01d262d2f0e874"
expected_axiom_report_hash = "sha256:a1ef77782ab68d41aede3e412c79174432934c3cac66c319dd2d406cf514f40e"
expected_certificate_hash = "sha256:5a5b68a51b3e90223f1e0cca730f8b155c79f881b9dca70d67e6bf10058054aa"
imports = []
inductives = ["Eq"]
definitions = []
theorems = []
axioms = []

[[modules]]
module = "Std.Nat.Basic"
source = "Std/Nat/Basic/source.npa"
certificate = "Std/Nat/Basic/certificate.npcert"
producer_profile = "std-library-legacy-core-builder"
expected_source_hash = "sha256:6e285573814d0eb4f6d658ff24127f5cfe0507b8b17d5b3f9b1b14a5bb641de6"
expected_certificate_file_hash = "sha256:d057dbc0e3c1e21649968eeaf882616602cfeb1f1cbb8393031c2010ea9596fb"
expected_export_hash = "sha256:30c432b4f2fc69e1e2414f556096e9d067d8e3d8e44f98bee1326169cccb5e4d"
expected_axiom_report_hash = "sha256:a1ef77782ab68d41aede3e412c79174432934c3cac66c319dd2d406cf514f40e"
expected_certificate_hash = "sha256:8a477f8d2becb4cfcb6a6baa1c79bc0112840cfe658302f47c9cf3dfd084d84e"
imports = []
inductives = ["Nat"]
definitions = []
theorems = []
axioms = []
